# Generated by Django 4.2.6 on 2023-10-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_be_rented', models.BooleanField(default=False)),
                ('transport_type', models.IntegerField(choices=[(0, 'Car'), (1, 'Bike'), (2, 'Scooter')], default=0)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=30)),
                ('identifier', models.CharField(max_length=10)),
                ('description', models.TextField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('minute_price', models.FloatField(null=True)),
                ('day_price', models.FloatField(null=True)),
            ],
        ),
    ]
