# Generated by Django 4.2.6 on 2023-10-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='active',
            new_name='is_active',
        ),
    ]
