# Generated by Django 4.2.6 on 2023-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rename_active_rent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='finish_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
