# Generated by Django 4.2.6 on 2023-10-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rent_finish_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='finish_datetime',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='created_datetime',
            new_name='time_start',
        ),
    ]
