# Generated by Django 4.2.6 on 2023-10-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_remove_rent_owner_id_rent_price_of_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='renter_id',
            new_name='user_id',
        ),
    ]
