# Generated by Django 4.2.6 on 2023-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rename_renter_id_rent_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='final_price',
            field=models.FloatField(null=True),
        ),
    ]
