# Generated by Django 4.2.6 on 2023-10-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_rent_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='is_active',
        ),
    ]
