# Generated by Django 4.2.6 on 2023-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_remove_rent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
