# Generated by Django 4.2.6 on 2023-10-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_transport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
